//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apartments
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Owner
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Owner()
        {
            this.Apartments = new HashSet<Apartment>();
        }

        public int IDOwner { get; set; }
        [Required]
        [MaxLength(50, ErrorMessage = "{0} must be up to 50 chars")]
        public string FirstName { get; set; }
        [Required]
        [MaxLength(50, ErrorMessage = "{0} must be up to 50 chars")]
        public string LastName { get; set; }

        public string FullName => $"{FirstName} {LastName}";

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Apartment> Apartments { get; set; }
    }
}
